// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoQLcX46Vz52HFOWI-gjAAGel3hny431I',
    appId: '1:392713519683:web:eb6270111e97eeecc98af6',
    messagingSenderId: '392713519683',
    projectId: 'cartivo-ecomarce',
    authDomain: 'cartivo-ecomarce.firebaseapp.com',
    storageBucket: 'cartivo-ecomarce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAAWTJFz-8Ab8jsXZwYRc8yf04fQc3nOM',
    appId: '1:392713519683:android:f04d5b208cd1df78c98af6',
    messagingSenderId: '392713519683',
    projectId: 'cartivo-ecomarce',
    storageBucket: 'cartivo-ecomarce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVBm-3ozVfJmSvvmZjRTGrBzLUzE-w-nM',
    appId: '1:392713519683:ios:c2cedfdd182b9361c98af6',
    messagingSenderId: '392713519683',
    projectId: 'cartivo-ecomarce',
    storageBucket: 'cartivo-ecomarce.firebasestorage.app',
    iosBundleId: 'com.example.cartivoMart',
  );
}
